INSERT INTO petdb.USER_SEQ (next_val) VALUES (50);
INSERT INTO petdb.u_Authority_SEQ (next_val) VALUES (50);

INSERT INTO petdb.ROLE (id, name) VALUES (1, 'ADMIN');
INSERT INTO petdb.ROLE (id, name) VALUES (2, 'USER');
INSERT INTO petdb.ROLE (id, name) VALUES (3, 'PET_USER');

INSERT INTO petdb.PRIVILEGE (id, name) VALUES (1, 'WRITE');
INSERT INTO petdb.PRIVILEGE (id, name) VALUES (2, 'READ');
INSERT INTO petdb.PRIVILEGE (id, name) VALUES (3, 'DELETE');

INSERT INTO petdb.ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID) VALUES (1, 1);
INSERT INTO petdb.ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID) VALUES (1, 2);
INSERT INTO petdb.ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID) VALUES (1, 3);
INSERT INTO petdb.ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID) VALUES (2, 2);
INSERT INTO petdb.ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID) VALUES (3, 1);
INSERT INTO petdb.ROLES_PRIVILEGES (ROLE_ID, PRIVILEGE_ID) VALUES (3, 2);

